---
- name: "Prerequisite install"
  hosts: all
  connection: local

  vars:
    vdo_disk: /dev/sda
    vdo_disk_name: vdo1
    vdo_logical_size: 200 
    repo_directory: /var/www/html/repos
    packags:
      - httpd 
      - httpd-tools
      - createrepo
      - yum-utils
      - vdo
      - kmod-kvdo
      - rsync

  tasks:

    - name: Install required packages before we start
      yum: pkg={{item}} state=installed enablerepo=rhel-7-server-rpms
      with_items:
        - "{{ packages }}"
      tags: packages

    - name: Ensure port 80 is allowed in firewalld
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes
      tags: firewall

    - name: Create VDO volume 
      vdo:
        name: "{{ vdo_disk_name }}"
        state: present
        running: yes
        activated: yes
        device: "{{ vdo_disk }}"
      tags: vdo

    - name: Format the VDO disk
      filesystem:
        fstype: xfs
        dev: "/dev/mapper/{{ vdo_disk_name }}"

    - name: Ensure repo dir exists
      file:
        path: "{{ repo_directory }}"
        state: directory
        mode: 0755

    - name: Ensure repo dir is mounted
      mount:
        path: "{{ repo_directory }}"
        src: "/dev/mapper/{{ vdo_disk_name }}"
        fstype: xfs
        opts: defaults,x-systemd.requires=vdo.service
        state: mounted

    - name: Ensure httpd is enabled and started
      systemd:
        name: httpd
        enabled: yes
        state: started
      tags: httpd
